### ISSUE TITLE
AssertionError [ERR_ASSERTION]: false == true

### ISSUE THREAD

**Issue by toomim** [indutny/spdy-transport#63] opened 2019-05-09 00:45 UTC
I've been periodically seeing this error in my app:

```
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: false == true
    at PriorityNode.removeChild (~/project/node_modules/spdy-transport/lib/spdy-transport/priority.js:74:3)
    at PriorityNode.remove (~/project/node_modules/spdy-transport/lib/spdy-transport/priority.js:62:15)
    at PriorityTree.add (~/project/node_modules/spdy-transport/lib/spdy-transport/priority.js:163:23)
    at Stream._initPriority (~/project/node_modules/spdy-transport/lib/spdy-transport/stream.js:101:25)
    at new Stream (~/project/node_modules/spdy-transport/lib/spdy-transport/stream.js:76:8)
    at Connection._createStream (~/project/node_modules/spdy-transport/lib/spdy-transport/connection.js:388:16)
    at Connection._handleHeaders (~/project/node_modules/spdy-transport/lib/spdy-transport/connection.js:436:21)
    at Connection._handleFrame (~/project/node_modules/spdy-transport/lib/spdy-transport/connection.js:319:10)
    at Parser.<anonymous> (~/project/node_modules/spdy-transport/lib/spdy-transport/connection.js:156:10)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at addChunk (~/project/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (~/project/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at Parser.Readable.push (~/project/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at Parser.Transform.push (~/project/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at next (~/project/node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:53:12)
    at ~/project/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/parser.js:72:5
    at ~/project/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/parser.js:293:5
    at done (~/project/node_modules/spdy-transport/lib/spdy-transport/utils.js:84:5)
    at next (~/project/node_modules/spdy-transport/lib/spdy-transport/utils.js:102:5)
    at afterWrite (~/project/node_modules/readable-stream/lib/_stream_writable.js:491:3)
    at _combinedTickCallback (internal/process/next_tick.js:144:20)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I'm sorry I don't have an actual test-case yet. This seems to happen when I open a number of tabs to different pages, and eventually I get a crash.

**Comment by jacobheun** [comment] 2019-05-09 08:26
This is a duplicate of https://github.com/spdy-http2/spdy-transport/issues/47 which is resolved.

**Closed as completed by jacobheun** 2019-05-09 08:26 UTC

**Comment by toomim** [comment] 2019-05-09 20:25
Thank you @jacobheun!
